name = "markdown"
main = "_worker.js"
compatibility_date = "2024-12-01"

assets = { directory = "public", binding = "ASSETS" }

kv_namespaces = [
  { binding = "SHARED_NOTES", id = "1868780cbfb64919be0732f89350e47e" }
]
